spring.application.name=taskmanager

# PostgreSQL Railway Config
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
taskmanager.app.jwtSecret=secretKeyForJwtTokenGenerationTeamTaskManagerProjectVeryLongAndSecure
taskmanager.app.jwtExpirationMs=86400000

# Server
server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEBUG